name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v5
    
    - name: Set up Node.js
      uses: actions/setup-node@v6
      with:
        node-version: '18'
        cache: 'npm'
    
    - name: Install dependencies
      run: npm run install:all
    
    - name: Lint frontend
      run: npm run lint:frontend
    
    - name: Lint backend
      run: npm run lint:backend

  test:
    name: Test
    runs-on: ubuntu-latest
    needs: lint
    
    services:
      postgres:
        image: postgres:latest
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: postgres
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    
    steps:
    - uses: actions/checkout@v5
    
    - name: Set up Node.js
      uses: actions/setup-node@v6
      with:
        node-version: '18'
        cache: 'npm'
    
    - name: Install dependencies
      run: npm run install:all
    
    - name: Create backend .env file
      run: |
        echo "DATABASE_URL=postgres://postgres:postgres@localhost:5432/postgres" > backend/.env
        echo "PORT=5000" >> backend/.env
    
    - name: Test frontend
      run: npm run test:frontend
    
    - name: Test backend
      run: npm run test:backend

  build:
    name: Build
    runs-on: ubuntu-latest
    needs: test
    
    steps:
    - uses: actions/checkout@v5
    
    - name: Set up Node.js
      uses: actions/setup-node@v6
      with:
        node-version: '18'
        cache: 'npm'
    
    - name: Install dependencies
      run: npm run install:all
    
    - name: Build frontend
      run: npm run build:frontend
    
    - name: Build backend
      run: npm run build:backend
    
    - name: Upload frontend build artifacts
      uses: actions/upload-artifact@v5
      with:
        name: frontend-build
        path: frontend/dist
    
    - name: Upload backend build artifacts
      uses: actions/upload-artifact@v5
      with:
        name: backend-build
        path: backend/dist